"use client";
import Navbar from "@/components/nav/nav";
import RiveGlowAnimation from "@/components/rive/RiveGlowAnimation";
import Contact from "@/components/section/contact";
import Footer from "@/components/section/footer";
import "./globals.css";
import Script from "next/script";
import { Suspense } from "react";
import Loading from "./loading";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// const RiveGlowAnimation = dynamic(
//   () => import("@/components/rive/RiveGlowAnimation"),
//   {
//     ssr: false, // since it's canvas-based and client-only
//   }
// );

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="overflow-x-clip">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>My Tender</title>
        <meta name="description" content="My Tender" />
        <link rel="icon" href="/favicon/favicon.ico" />
        <link rel="icon" href="/favicon/favicon-16x16.png" />
        <link rel="icon" href="/favicon/favicon-32x32.png" />
        <link rel="icon" href="/favicon/android-chrome-192x192.png" />
        <link rel="icon" href="/favicon/android-chrome-512x512.png" />
        <link rel="icon" href="/favicon/apple-touch-icon.png" />
        <link rel="manifest" href="/favicon/site.webmanifest" />
      </head>
      <body
        suppressHydrationWarning
        className={`antialiased w-screen p-0`}
        style={{
          overflow: "clip",
        }}
      >
        <Suspense fallback={<Loading />}>
          <div className="h-fit w-full relative">
            <RiveGlowAnimation />
            {/* <div className="absolute w-full overflow-hidden h-screen top-[-30%] md:top-[-20%] lg:top-[0%] xl:top-[0] z-[-1]">
          <RiveComponent className="w-full h-full scale-150 lg:scale-200 blur-xl mt-40 bg-transparent" />
        </div> */}
            <Navbar />
            <div className="bg-gradient-to-t from-[#fff] via-[#fff] via-[80%] to-[#fff0] w-full h-[150vh] absolute top-[-2%] md:top-[3%] left-0 -z-10" />
            {children}
            <Contact />
            <Footer />
          </div>
        </Suspense>
        <Script
          id="hs-script-loader"
          src="//js-eu1.hs-scripts.com/144606585.js"
          strategy="afterInteractive"
          async
          defer
        />
      </body>
    </html>
  );
}
